// File: taskflow-cloud/frontend/src/app/files/page.js
// Purpose: Dedicated page showing all files uploaded to AWS S3
// Why: Makes it visually clear that S3 is being used for file storage

'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Cookies from 'js-cookie';
import toast from 'react-hot-toast';
import Navbar from '@/components/Navbar';
import { fileAPI } from '@/lib/api';

// Helper: return a nice icon based on file type
function FileIcon({ mimeType }) {
  if (mimeType?.startsWith('image/')) return '🖼️';
  if (mimeType === 'application/pdf') return '📄';
  if (mimeType?.includes('word')) return '📝';
  return '📎';
}

// Helper: format bytes into readable size
function formatSize(bytes) {
  if (!bytes) return '—';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export default function FilesPage() {
  const router = useRouter();
  const [files, setFiles] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!Cookies.get('taskflow_token')) {
      router.push('/login');
      return;
    }
    loadFiles();
  }, []);

  const loadFiles = async () => {
    try {
      const res = await fileAPI.getMyFiles();
      setFiles(res.data.data.files);
    } catch {
      toast.error('Failed to load files');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (fileId, originalName) => {
    try {
      const res = await fileAPI.getDownloadUrl(fileId);
      window.open(res.data.data.download_url, '_blank');
      toast.success('Download started!');
    } catch {
      toast.error('Failed to get download link');
    }
  };

  const handleDelete = async (fileId) => {
    if (!confirm('Delete this file from S3? This cannot be undone.')) return;
    try {
      await fileAPI.deleteFile(fileId);
      toast.success('File deleted from S3');
      loadFiles();
    } catch {
      toast.error('Failed to delete file');
    }
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      <main className="max-w-5xl mx-auto px-6 py-8">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-gray-900">Files</h1>
          <p className="text-gray-500 text-sm mt-1">
            All files are stored in <span className="font-semibold text-orange-600">AWS S3</span>. 
            Downloads use signed URLs (expire after 1 hour for security).
          </p>
        </div>

        {/* AWS S3 Info Badge */}
        <div className="bg-orange-50 border border-orange-200 rounded-xl p-4 mb-6 flex items-center gap-3">
          <span className="text-2xl">☁️</span>
          <div>
            <p className="font-semibold text-orange-800">Connected to AWS S3</p>
            <p className="text-orange-700 text-sm">
              Files are securely stored in Amazon S3 with server-side encryption (AES-256).
              Download links are temporary signed URLs generated by the backend.
            </p>
          </div>
        </div>

        {/* Files Count */}
        <div className="bg-white rounded-xl shadow-sm p-4 mb-4">
          <p className="text-gray-600 text-sm">
            Total files: <span className="font-bold text-gray-900">{files.length}</span>
          </p>
        </div>

        {/* Files Table */}
        {loading ? (
          <div className="text-center py-12 text-gray-400">Loading files from S3...</div>
        ) : files.length === 0 ? (
          <div className="text-center py-16 bg-white rounded-xl shadow-sm">
            <p className="text-4xl mb-3">📁</p>
            <p className="text-gray-500">No files uploaded yet.</p>
            <p className="text-gray-400 text-sm mt-1">
              Go to any task and upload a file to see it here.
            </p>
            <button
              onClick={() => router.push('/projects')}
              className="mt-4 bg-blue-600 text-white px-4 py-2 rounded-lg text-sm hover:bg-blue-700"
            >
              Go to Projects
            </button>
          </div>
        ) : (
          <div className="bg-white rounded-xl shadow-sm overflow-hidden">
            <table className="w-full">
              <thead className="bg-gray-50 border-b border-gray-200">
                <tr>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase">File</th>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase">Task</th>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase">Size</th>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase">Uploaded</th>
                  <th className="text-left px-4 py-3 text-xs font-semibold text-gray-500 uppercase">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                {files.map((file) => (
                  <tr key={file.id} className="hover:bg-gray-50">
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        <span className="text-xl"><FileIcon mimeType={file.mime_type} /></span>
                        <div>
                          <p className="text-sm font-medium text-gray-900 max-w-xs truncate">
                            {file.original_name}
                          </p>
                          <p className="text-xs text-gray-400">{file.mime_type}</p>
                        </div>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <p className="text-sm text-gray-700">{file.task_title || '—'}</p>
                      <p className="text-xs text-gray-400">{file.project_name || '—'}</p>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-600">
                      {formatSize(file.file_size)}
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-500">
                      {new Date(file.created_at).toLocaleDateString()}
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleDownload(file.id, file.original_name)}
                          className="text-xs bg-blue-100 text-blue-700 hover:bg-blue-200 px-2 py-1 rounded"
                        >
                          ↓ Download
                        </button>
                        <button
                          onClick={() => handleDelete(file.id)}
                          className="text-xs bg-red-100 text-red-600 hover:bg-red-200 px-2 py-1 rounded"
                        >
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </main>
    </div>
  );
}